version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: fastreading-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fast_reading_db
      MYSQL_USER: fast_reading_db
      MYSQL_PASSWORD: tUEMBQRW7FqcCW9gf95U
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
